use std::collections::HashMap;
use std::sync::LazyLock;

use anyhow::{bail, format_err, Error};
use parking_lot::RwLock;
use serde::{Deserialize, Serialize};
use serde_json::{from_value, Value};

use proxmox_sys::fs::CreateOptions;

use pbs_api_types::Authid;
//use crate::auth;
use crate::{open_backup_lockfile, BackupLockGuard};

const LOCK_FILE: &str = pbs_buildcfg::configdir!("/token.shadow.lock");
const CONF_FILE: &str = pbs_buildcfg::configdir!("/token.shadow");

/// Global in-memory cache for successfully verified API token secrets.
/// The cache stores plain text secrets for token Authids that have already been
/// verified against the hashed values in `token.shadow`. This allows for cheap
/// subsequent authentications for the same token+secret combination, avoiding
/// recomputing the password hash on every request.
static TOKEN_SECRET_CACHE: LazyLock<RwLock<ApiTokenSecretCache>> = LazyLock::new(|| {
    RwLock::new(ApiTokenSecretCache {
        secrets: HashMap::new(),
        shared_gen: 0,
    })
});

#[derive(Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
/// ApiToken id / secret pair
pub struct ApiTokenSecret {
    pub tokenid: Authid,
    pub secret: String,
}

// Get exclusive lock
fn lock_config() -> Result<BackupLockGuard, Error> {
    open_backup_lockfile(LOCK_FILE, None, true)
}

fn read_file() -> Result<HashMap<Authid, String>, Error> {
    let json = proxmox_sys::fs::file_get_json(CONF_FILE, Some(Value::Null))?;

    if json == Value::Null {
        Ok(HashMap::new())
    } else {
        // swallow serde error which might contain sensitive data
        from_value(json).map_err(|_err| format_err!("unable to parse '{}'", CONF_FILE))
    }
}

fn write_file(data: HashMap<Authid, String>) -> Result<(), Error> {
    let backup_user = crate::backup_user()?;
    let options = CreateOptions::new()
        .perm(nix::sys::stat::Mode::from_bits_truncate(0o0640))
        .owner(backup_user.uid)
        .group(backup_user.gid);

    let json = serde_json::to_vec(&data)?;
    proxmox_sys::fs::replace_file(CONF_FILE, &json, options, true)
}

/// Verifies that an entry for given tokenid / API token secret exists
pub fn verify_secret(tokenid: &Authid, secret: &str) -> Result<(), Error> {
    if !tokenid.is_token() {
        bail!("not an API token ID");
    }

    // Fast path
    if cache_try_secret_matches(tokenid, secret) {
        return Ok(());
    }

    // Slow path
    // First, capture the shared generation before doing the hash verification.
    let gen_before = token_shadow_shared_gen();

    let data = read_file()?;
    match data.get(tokenid) {
        Some(hashed_secret) => {
            proxmox_sys::crypt::verify_crypt_pw(secret, hashed_secret)?;

            // Try to cache only if nothing changed while verifying the secret.
            if let Some(gen_before) = gen_before {
                cache_try_insert_secret(tokenid.clone(), secret.to_owned(), gen_before);
            }

            Ok(())
        }
        None => bail!("invalid API token"),
    }
}

/// Generates a new secret for the given tokenid / API token, sets it then returns it.
/// The secret is stored as salted hash.
pub fn generate_and_set_secret(tokenid: &Authid) -> Result<String, Error> {
    let secret = format!("{:x}", proxmox_uuid::Uuid::generate());
    set_secret(tokenid, &secret)?;
    Ok(secret)
}

/// Adds a new entry for the given tokenid / API token secret. The secret is stored as salted hash.
fn set_secret(tokenid: &Authid, secret: &str) -> Result<(), Error> {
    if !tokenid.is_token() {
        bail!("not an API token ID");
    }

    let guard = lock_config()?;

    let mut data = read_file()?;
    let hashed_secret = proxmox_sys::crypt::encrypt_pw(secret)?;
    data.insert(tokenid.clone(), hashed_secret);
    write_file(data)?;

    apply_api_mutation(guard, tokenid, Some(secret));

    Ok(())
}

/// Deletes the entry for the given tokenid.
pub fn delete_secret(tokenid: &Authid) -> Result<(), Error> {
    if !tokenid.is_token() {
        bail!("not an API token ID");
    }

    let guard = lock_config()?;

    let mut data = read_file()?;
    data.remove(tokenid);
    write_file(data)?;

    apply_api_mutation(guard, tokenid, None);

    Ok(())
}

/// Cached secret.
struct CachedSecret {
    secret: String,
}

struct ApiTokenSecretCache {
    /// Keys are token Authids, values are the corresponding plain text secrets.
    /// Entries are added after a successful on-disk verification in
    /// `verify_secret` or when a new token secret is generated by
    /// `generate_and_set_secret`. Used to avoid repeated
    /// password-hash computation on subsequent authentications.
    secrets: HashMap<Authid, CachedSecret>,
    /// Shared generation to detect mutations of the underlying token.shadow file.
    shared_gen: usize,
}

impl ApiTokenSecretCache {
    /// Resets all local cache contents and sets/updates the cached generation.
    fn reset_and_set_gen(&mut self, new_gen: usize) {
        self.secrets.clear();
        self.shared_gen = new_gen;
    }

    /// Caches a secret and sets/updates the cache generation.
    fn insert_and_set_gen(&mut self, tokenid: Authid, secret: CachedSecret, new_gen: usize) {
        self.secrets.insert(tokenid, secret);
        self.shared_gen = new_gen;
    }

    /// Evicts a cached secret and sets/updates the cached generation.
    fn evict_and_set_gen(&mut self, tokenid: &Authid, new_gen: usize) {
        self.secrets.remove(tokenid);
        self.shared_gen = new_gen;
    }
}

fn cache_try_insert_secret(tokenid: Authid, secret: String, shared_gen_before: usize) {
    let Some(mut cache) = TOKEN_SECRET_CACHE.try_write() else {
        return;
    };

    let Some(shared_gen_now) = token_shadow_shared_gen() else {
        return;
    };

    // If this process missed a generation bump, its cache is stale.
    if cache.shared_gen != shared_gen_now {
        cache.reset_and_set_gen(shared_gen_now);
    }

    // If a mutation happened while we were verifying the secret, do not insert.
    if shared_gen_now == shared_gen_before {
        cache.insert_and_set_gen(tokenid, CachedSecret { secret }, shared_gen_now);
    }
}

/// Tries to match the given token secret against the cached secret.
///
/// Verifies the generation/version before doing the constant-time
/// comparison to reduce TOCTOU risk. During token rotation or deletion
/// tokens for in-flight requests may still validate against the previous
/// generation.
fn cache_try_secret_matches(tokenid: &Authid, secret: &str) -> bool {
    let Some(cache) = TOKEN_SECRET_CACHE.try_read() else {
        return false;
    };
    let Some(entry) = cache.secrets.get(tokenid) else {
        return false;
    };
    let Some(current_gen) = token_shadow_shared_gen() else {
        return false;
    };

    if current_gen == cache.shared_gen {
        let cached_secret_bytes = entry.secret.as_bytes();
        let secret_bytes = secret.as_bytes();

        return cached_secret_bytes.len() == secret_bytes.len()
            && openssl::memcmp::eq(cached_secret_bytes, secret_bytes);
    }

    false
}

fn apply_api_mutation(_guard: BackupLockGuard, tokenid: &Authid, new_secret: Option<&str>) {
    // Signal cache invalidation to other processes (best-effort).
    let bumped_gen = bump_token_shadow_shared_gen();

    let mut cache = TOKEN_SECRET_CACHE.write();

    // If we cannot get the current generation, we cannot trust the cache
    let Some(current_gen) = token_shadow_shared_gen() else {
        cache.reset_and_set_gen(0);
        return;
    };

    // If we cannot bump the shared generation, or if it changed after
    // obtaining the cache write lock, we cannot trust the cache
    if bumped_gen != Some(current_gen) {
        cache.reset_and_set_gen(current_gen);
        return;
    }

    // Apply the new mutation.
    match new_secret {
        Some(secret) => {
            let cached_secret = CachedSecret {
                secret: secret.to_owned(),
            };
            cache.insert_and_set_gen(tokenid.clone(), cached_secret, current_gen);
        }
        None => cache.evict_and_set_gen(tokenid, current_gen),
    }
}

/// Get the current shared generation.
fn token_shadow_shared_gen() -> Option<usize> {
    crate::ConfigVersionCache::new()
        .ok()
        .map(|cvc| cvc.token_shadow_generation())
}

/// Bump and return the new shared generation.
fn bump_token_shadow_shared_gen() -> Option<usize> {
    crate::ConfigVersionCache::new()
        .ok()
        .map(|cvc| cvc.increase_token_shadow_generation() + 1)
}
